### ISSUE TITLE
[FEATURE] Add Request and Response Bodies for 4 main Point-in-time endpoints

### ISSUE THREAD

**Issue by nhtruong** [opensearch-project/opensearch-api-specification#100]
There are [6 PIT actions](https://opensearch.org/docs/latest/point-in-time-api/) that was added to OS 2.4. The following 4 currently do not have Request and Response bodies:
- **create_pit**: `POST {index}/_search/point_in_time`
- **get_all_pits**: `GET _search/point_in_time/_all`
- **delete_all_pits**: `DELETE _search/point_in_time/_all`
- **delete_pit**: `DELETE _search/point_in_time`

Follow the [Developer's Guide](./DEVELOPER_GUIDE.md) doc to fill in the missing info.
You might have to manually make calls to an OS cluster to figure out the shape of the response bodies.

NOTE: Don't work on this issue until https://github.com/opensearch-project/opensearch-api-specification/pull/91 has been merged.

**Comment by Tokesh** [comment]
Hello everyone!
We discussed at the meeting with @nhtruong , that @aabeshov and I will do this issue!

**Comment by Tokesh** [comment]
Hello everyone! 
We have fortunately made this issue and are waiting for your comments about our work!

P.S. We divide it to 2 PR, because we have some problems with counting of job in our CCI program
@aabeshov provided Request and Response Bodies for [create_pit and delete_all_pits](https://github.com/opensearch-project/opensearch-api-specification/pull/104)
I provided Request and Response Bodies for [get_all_pits and delete_pit](https://github.com/opensearch-project/opensearch-api-specification/pull/105)
If its not comfortable for checking or merging, we will definitely discuss this in our conference of CCI and will do it in the future in one pull request

**Comment by VachaShah** [comment]
> Hello everyone! We have fortunately made this issue and are waiting for your comments about our work!
> 
> P.S. We divide it to 2 PR, because we have some problems with counting of job in our CCI program @aabeshov provided Request and Response Bodies for [create_pit and delete_all_pits](https://github.com/opensearch-project/opensearch-api-specification/pull/104) I provided Request and Response Bodies for [get_all_pits and delete_pit](https://github.com/opensearch-project/opensearch-api-specification/pull/105) If its not comfortable for checking or merging, we will definitely discuss this in our conference of CCI and will do it in the future in one pull request. We had no experience in production or open source development before and we are just learning!

Thank you @Tokesh and @aabeshov for contributing! The division into PRs is totally fine. Will review the PRs.

**Comment by VachaShah** [comment]
Done in #104 and #105
