### ISSUE TITLE
Put Index Mapping API

### ISSUE THREAD

**Issue by pgtgrly** [opensearch-project/opensearch-api-specification#6]

**Comment by SOPHIA2401** [comment]
Due to a documentation error, the `PUT /_mappings` API is currently not functional. I have raised an issue about it (https://github.com/opensearch-project/documentation-website/issues/565).
Once we have the support to this API, we must modify the test case and hooks file for testing the `PUT /_mappings` and `PUT {index}/ _mappings` operation.
