### ISSUE TITLE
[BUG] RequestBodies schema type conflicts with the header

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/opensearch-api-specification#656]
### What is the bug?
Separate from https://github.com/opensearch-project/opensearch-api-specification/issues/633

For example `/_bulk`, we specify the `requestBodies` for `bulk` as an **array** which conflicts with the `application/x-ndjson` format, which uses newline-delimited JSON rather than a JSON array. 

Ref:
https://github.com/opensearch-project/opensearch-api-specification/blob/07e329e8d01fd0576de6a0a3c35412fd5a9163db/spec/namespaces/_core.yaml#L2256-L2259

### What is the expected behavior?
We should specify whichever schema for `application/x-ndjson` as a **String**.

**Comment by Xtansia** [comment]
We need to represent the structure that is being returned or accepted by the API. It is an array of objects, just encoded in a certain manner, which is indicated by what the content type is.
This is not much different to the way things like XML would be represented: https://swagger.io/docs/specification/v3_0/data-models/representing-xml/

**Comment by dblock** [comment]
@Xtansia Are you seeing this is a non-issue and represented correctly? @zelinh do you disagree? otherwise close this?

**Comment by zelinh** [comment]
@Xtansia Thanks for the reply. While I think the correct structure to represent this should be String. As we specify it as Newline delimited JSON, It's slightly different from the simple array or json structure. This can cause error when we run any schema validation.

**Comment by Xtansia** [comment]
@zelinh Which schema validation are you referring to? It is still structured data not a plain string, and the encoding is determined by what the content type is, which any validation or (de)serialization must take into account. Otherwise this also applies to [cbor & smile](https://github.com/opensearch-project/opensearch-api-specification/blob/main/spec/namespaces/cat.yaml#L882-L906).

Additionally we need the structure information for client code generation.

**Comment by zelinh** [comment]
I see. Thanks for the context here. I think we could close out this issue then as this is by design.
